### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by biswa1751** [Chris1234567899/flutter_time_range_picker#14]
Dart 2.12 and flutter 2.0.0 are now in stable with the null-safety feature.
Any plan to support Null Safety @Chris1234567899 .

Here's an official guide from dart doc
https://dart.dev/null-safety/migration-guide

**Comment by Chris1234567899** [comment]
Good call I just updated it. Version 2.0.0 is online.

Let me know if you encounter any problems.

**Comment by deanriverson** [comment]
Thank you!  This was the last dependency that was keeping my app from sound null safety.

I was contemplating submitting a PR for the feature, but you beat me to it.  I wanted to ask how you prefer PRs to be submitted.  Any particular process or formatting or anything?

Thanks again!

**Comment by Chris1234567899** [comment]
You're welcome.
If you want to make PRs in the future, no problem, no special formatting needed.
