### ISSUE TITLE
"ticks" cannot show in version ^2.0.0

### ISSUE THREAD

**Issue by WingCH** [Chris1234567899/flutter_time_range_picker#16]
in example first button, ticks is "12", but TimeRangePicker receive wrong `ticks` number

![image](https://user-images.githubusercontent.com/19588517/110900197-5a876b00-833d-11eb-9a16-82851b04ad76.png)

![Screenshot_2021-03-12-14-21-21-562_com example example](https://user-images.githubusercontent.com/19588517/110900944-81926c80-833e-11eb-80a2-79981ff4f278.jpg)

**Comment by Chris1234567899** [comment]
Sorry about that, I fixed it.
