### ISSUE TITLE
Interval not works

### ISSUE THREAD

**Issue by TolgaYld** [Chris1234567899/flutter_time_range_picker#17]
Hi,

i dont think it works.

i have always time steps of 5 minutes.

> onPressed: () async {
>             TimeRange result = await showTimeRangePicker(
>               selectedColor: Theme.of(context).accentColor,
>               use24HourFormat: true,
>               interval: Duration(minutes: 15),
>               context: context,
>             );
>             print("result " + result.toString());
>           },

**Comment by Chris1234567899** [comment]
Sorry, a bug during the change to 2.0.0, I fixed it, check out 2.0.1
