### ISSUE TITLE
Is it possible to implement an adaptive dialog?

### ISSUE THREAD

**Issue by TolgaYld** [Chris1234567899/flutter_time_range_picker#19]
first of all, many thanks for this great package and great support.  👍😄

I thought of something. Is it possible to make the UI adaptive? For IOS and Android?

I don't know if Apple would say anything if you want to release an app with this package.

A suggestion and a question at the same time. 🙃

Greetings and thaaanks!

**Comment by Chris1234567899** [comment]
I added an example for a custom cupertino style like dialog.
