### ISSUE TITLE
Cancel button gives null safety error

### ISSUE THREAD

**Issue by suthura** [Chris1234567899/flutter_time_range_picker#22]
When I click the cancel button it gives   

> type 'Null' is not a subtype of type 'TimeRange'

  error.
I went through the plugin code and found that your cancel method is also requesting **TimeRange**

![image](https://user-images.githubusercontent.com/33677834/126511051-5a62cba7-f8c1-4da8-b867-a9227b2c9824.png)

Please check this out and waiting for a update. Thank you.

**Comment by Chris1234567899** [comment]
Sorry, I cannot reproduce your error.

The resulting TimeRange can of course be null (if the user presses cancel) or goes back via the back button etc. 

Just call it like:
```
TimeRange? result = await showTimeRangePicker(
       context: context,
);
```

**Comment by suthura** [comment]
fixed thank you for the support
