### ISSUE TITLE
Bug - Date range goes beyond 24 hrs.

### ISSUE THREAD

**Issue by Harishwarrior** [Chris1234567899/flutter_time_range_picker#26]
Using the latest version.

![Screenshot_20211027-122821](https://user-images.githubusercontent.com/38380040/139016138-2cfb83e9-c5b5-4aab-abc7-1556ae34fa85.jpg)

**Comment by Chris1234567899** [comment]
Thanks for reporting, I could replicate this issue.
I assume, you are using the maxDuration parameter when this happens? 
Or did it happen without it also?
Can you confirm pls?

**Comment by Harishwarrior** [comment]
> Thanks for reporting, I could replicate this issue. I assume, you are using the maxDuration parameter when this happens? Or did it happen without it also? Can you confirm pls?


I tried with maxDuration parameter set to 2 hours and this issue shows up. But, didn't tested without maxDuration.

**Comment by Chris1234567899** [comment]
This should be fixed now with 2.1.0

**Comment by Harishwarrior** [comment]
> This should be fixed now with 2.1.0

Thanks
