### ISSUE TITLE
support many disableTime ？

### ISSUE THREAD

**Issue by iceshu** [Chris1234567899/flutter_time_range_picker#27]
it can support many disableTimes like this:

8:00-9:00 disable

12:3:00 disable。

**Comment by Chris1234567899** [comment]
Double, see https://github.com/Chris1234567899/flutter_time_range_picker/issues/9

Would be nice, I agree, but hard to implement, since the user would have to be able to jump around between different time segments, even be able to select more than one time ranges.

Open for PR ;-)
