### ISSUE TITLE
looking so large in web app

### ISSUE THREAD

**Issue by rawquesh** [Chris1234567899/flutter_time_range_picker#29]
hey Chris, really like your package, I am currently using this in a web project but it's looking so weirdly large, i would like to know if there is an option to manage the size of it, thank you.

![Screenshot (630)](https://user-images.githubusercontent.com/27288409/144226978-fd97bd71-6c94-4e2d-bb2b-49d71805bde0.png)

**Comment by Chris1234567899** [comment]
Ok. Right now, I see two options here:

1. If you don't need the dialog, you can implement it as a widget (see example) and just size the parent to your liking.
2. If you do want to have the dialog, you can use meanwhile a custom one (see also example) and style it accordingly.

I will think about adding parameters for this, but it might take a while.

**Comment by rawquesh** [comment]
thank you, for now, I am using a custom one.
