### ISSUE TITLE
[BUG] showCupertinoDialog() return the same start and end values

### ISSUE THREAD

**Issue by TolgaYld** [Chris1234567899/flutter_time_range_picker#31]
Hi :),

i test the cupertinoTheme but i see a bug. In this case: "TimeRange? result = await showCupertinoDialog()" the result.endTime has the same value with result.startTime. It would be cool if u can fix that.

A suggestion:
It would be cool if i can set the padding property in the TimeRangePicker class more individual. For example i want to have a padding on the top of the circle but if i write a value in the padding property the whole circle shrinks.

Thanks in advance and happy christmas :)!

**Comment by TolgaYld** [comment]
any updates?

**Comment by Chris1234567899** [comment]
Hi, sorry, been kind of busy with other stuff lately.
I checked but could not reproduce your issue. Did you check the example?
Can you post the code you're using?
