### ISSUE TITLE
Warnings after upgrading to Flutter 3.0.0

### ISSUE THREAD

**Issue by pst9354** [Chris1234567899/flutter_time_range_picker#38]
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/time-range-dialog.dart:306
../…/src/time-range-dialog.dart:334
../…/src/time-range-dialog.dart:341
../…/src/time-range-dialog.dart:348

**Comment by allyssonmast** [comment]
up

**Comment by Chris1234567899** [comment]
Will be addressed in the next update, coming soon.

**Comment by Xellly** [comment]
Why did you close this and then disappear?
