### ISSUE TITLE
How can I customize the header?

### ISSUE THREAD

**Issue by cywaaa** [Chris1234567899/flutter_time_range_picker#39]
How can I customize the header in general? I want to customize the background color and text color of "from" and "to". I already tried changing the ThemeData.

![image](https://user-images.githubusercontent.com/24358013/169937395-bfb6de1f-307b-44e6-9d0f-7515708769cd.png)

**Comment by Chris1234567899** [comment]
You have control over the background color through the primarySwatch variable of your theme data.
Additionally, you can control text styles by the parameters:
  TextStyle? timeTextStyle
  TextStyle? activeTimeTextStyle
  
  If that is not enough, you always have the option to create a custom dialog and use the widget within, setting hideTimes to true and implement your own header - see the custom dialog example.
