### ISSUE TITLE
Getting warning flutter update

### ISSUE THREAD

**Issue by rp01** [Chris1234567899/flutter_time_range_picker#40]
Local/Pub/Cache/hosted/pub.dartlang.org/time_range_picker-2.1.0/lib/src/time-range-dialog.dart:348:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback((_) => setRadius());

My flutter version : 3.0.1

**Comment by zeeboydrummer** [comment]
Getting the same error.

../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/time_range_picker-2.1.0/lib/src/time-range-dialog.dart:306:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../sdk/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);

**Comment by Chris1234567899** [comment]
Should be fixed with 2.2.0
