### ISSUE TITLE
Midnight has 2 steps (both 0:00 and 24:00)

### ISSUE THREAD

**Issue by Fleximex** [Chris1234567899/flutter_time_range_picker#5]
When choosing a time I can choose both 0:00 and 24:00 as the time for midnight (2 different steps). The time 24:00 is barely used anymore and should be removed.

**Comment by Chris1234567899** [comment]
You mean when choosing a start time for example?

**Comment by Fleximex** [comment]
Yes. Both 0:00 and 24:00 are separate steps when choosing a time.

**Comment by Chris1234567899** [comment]
fixed and released under 1.1.0
