### ISSUE TITLE
onConfirm Function

### ISSUE THREAD

**Issue by AntoliniMatteo** [Chris1234567899/flutter_time_range_picker#8]
Can you please add onConfirm(TimeOfDay startTime, TimeOfDay endTime)?

**Comment by Chris1234567899** [comment]
I don't think that this is necessary.
You can get the times like this:
```
             TimeRange result = await showTimeRangePicker(
              context: context,
            );
            print("result " + result.toString());
```

TimeRange contains the start and end times and the result will be null if the user did not click the confirm button.
